### ISSUE TITLE
Update the disjunction macro to use new JuMP extension API

### ISSUE THREAD

**Issue by odow** [hdavid16/DisjunctiveProgramming.jl#103]
Following https://github.com/jump-dev/JuMP.jl/issues/3513#issuecomment-1757920537

What is the full range of syntax you want the macro to support? Why even have a macro? What is the trade-off of just having a functional form?

**Comment by pulsipher** [comment]
For `@disjunction`, the main motivation for the macro is container creation. It is a common use-case to create disjunctions over sets. It is not currently used for an any specialized expression parsing, though this may be added in the future. One complicating factor for `@disjunction` is that is it tricky to distinguish the anonymous singleton case from the vectorized case which is what leads to most of the complexity. 

From the JuMP extension perspective, it would be nice to not have to duplicate all the helper methods:
https://github.com/hdavid16/DisjunctiveProgramming.jl/blob/d7e8e7a09b1cb39d628b25d9a0cded2345c9664d/src/macros.jl#L1-L133
A lot of repetition of JuMP-like macro code happens when making the build calls that potentially create containers and parse naming:
https://github.com/hdavid16/DisjunctiveProgramming.jl/blob/d7e8e7a09b1cb39d628b25d9a0cded2345c9664d/src/macros.jl#L230-L260

**Comment by pulsipher** [comment]
Now that Oscar has finished his public API for macro extensions in JuMP and released them in the latest release, we should update the macros to use the API. This should simply the macro code quite a bit :)

**Comment by pulsipher** [comment]
This was fixed with #110.
